/* Generated By:JavaCC: Do not edit this line. FormulaEvaluatorConstants.java */
package br.cefetrj.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaEvaluatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER_OF_VERTICES = 4;
  /** RegularExpression Id. */
  int NUMBER_OF_EDGES = 5;
  /** RegularExpression Id. */
  int EIGENVALUE_IDENTIFIER = 6;
  /** RegularExpression Id. */
  int IDENTIFIER_WITH_OVERLINE = 7;
  /** RegularExpression Id. */
  int EULER_CONSTANT = 8;
  /** RegularExpression Id. */
  int CHROMATIC_NUMBER = 9;
  /** RegularExpression Id. */
  int LARGEST_CLIQUE_SIZE = 10;
  /** RegularExpression Id. */
  int LARGEST_DEGREE_IDENTIFIER = 11;
  /** RegularExpression Id. */
  int INT_CONST = 12;
  /** RegularExpression Id. */
  int DBL_CONST = 13;
  /** RegularExpression Id. */
  int EXPONENT = 14;
  /** RegularExpression Id. */
  int DIGITS = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int EOL = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int POWER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"ORDER\"",
    "\"SIZE\"",
    "<EIGENVALUE_IDENTIFIER>",
    "<IDENTIFIER_WITH_OVERLINE>",
    "\"\\\\exp\"",
    "\"\\\\chi\"",
    "\"\\\\omega\"",
    "<LARGEST_DEGREE_IDENTIFIER>",
    "<INT_CONST>",
    "<DBL_CONST>",
    "<EXPONENT>",
    "<DIGITS>",
    "<DIGIT>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\frac{\"",
    "\"}\"",
    "\"{\"",
    "\"(\"",
    "\")\"",
  };

}
